### ISSUE TITLE
Android non branch deep link sometimes not available

### ISSUE THREAD

**Issue by vasa137** [RodrigoSMarques/flutter_branch_sdk#308]
**Describe the bug**
When I try to open the app with the non-branch deep link, non_branch_link field sometimes doesn't provide the url I've clicked on. 

**To Reproduce**
1. I've clicked on the link with the custom domain: dev-app.operi.rs/home/orders
2. Branch SDK logged this D/FlutterBranchSDK( 3719): BranchReferralInitListener - params: {"+non_branch_link":"dev-operi-app:\/\/open?link_click_id=1304070486333205728","+clicked_branch_link":false,"+is_first_session":false}
3. listSession method returned this value in the callback

**Expected behavior**
I've expected to get non_branch_link = dev-app.operi.rs/home/orders

**Smartphone (Please complete the following information. remove session if not platform):**
 - Flutter: version: 3.19.2
 - Package version: 7.3.0
 - OS: Android 14
 - Device: Samsung Galaxy S21 FE
 
 - **Additional context**

In some periods of the day - the expect behavior is happening, but mostly it returns dev-operi-app:\/\/open?link_click_id=XXX. Also, on Xiaomi I've never received this type of the response - it's always the original link.

**Comment by RodrigoSMarques** [comment]
Hi @vasa137 .

This package calls Branch Native SDK functions on each platform.

The problem reported is not in the Flutter plugin, but in the Native SDK.

Please open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)

Or open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket)

**Comment by kalismeras61** [comment]
@RodrigoSMarques i am also having same issue, open?link_click_id=1304070486333205728. instead of returning no branch uri 

How we can handle this?

**Comment by vasa137** [comment]
I think the only option is to Generate the link on the Branch portal - since nonBranch links which are using the same domain you registered on Branch Portal will return this thing....

I reached support - but no luck.

**Comment by RodrigoSMarques** [comment]
I believe I have identified the problem. I'm already working on the next version. It will be made available in the next few days.

**Comment by kalismeras61** [comment]
@RodrigoSMarques any update ?

**Comment by RodrigoSMarques** [comment]
> @RodrigoSMarques any update ?

Reviewing the documentation, as there will be changes to the `init` method and the way to activate the test key. It will no longer be possible to configure via code.

**Comment by RodrigoSMarques** [comment]
@kalismeras61  @vasa137 

Version 8.0.0 released.

Take the tests and report the results.

**Comment by vasa137** [comment]
Hey @RodrigoSMarques I checked new version - looks like this issue is solved - but another big issue is there can you please check - [#325 ](https://github.com/RodrigoSMarques/flutter_branch_sdk/issues/325)

**Comment by vasa137** [comment]
Looks like it's solved in version 8.0.1 - I will monitor it a little bit more - since it was working from time to time before - looks promising until now.

**Comment by vasa137** [comment]
Hello, it stopped working completely recently. I noticed issues in my app (using version 8.2.0).
So non_branch_link again shows some weird things (link_click_id) without path

I was testing with: https://app.operi.rs/home/profile and I get in the flutter app - operi-app//?link_click_id=...

Can you please fix again?

**Comment by RodrigoSMarques** [comment]
@vasa137 

I couldn't understand the scenarios you reported.

Remember that when clicking on a deeplink, Branch services (API) are responsible for returning the data.

The plugin only bridges the gap between the native code and Dart.

If the data returned for a deeplink is incorrect, it is due to the Branch API return, not the plugin.

Note: If the application was in the foreground, goes to the background and returns, the Branch SDK always "restarts" the return data.

**Comment by vasa137** [comment]
> I believe I have identified the problem. I'm already working on the next version. It will be made available in the next few days.

But few months ago, you identified the issue an it was working fine, now the issue is happening again.

**Comment by 0aps** [comment]
@RodrigoSMarques this is still happening in 8.3.2. Only happens in Android, iOS works fine. Basically, `non_branch_link` value is never the url that was opened, it always translate to the url schema version of the app.  I noticed in the Branch.io dashboard config we have a "URI Scheme Deep Link Mode" field but even if I fully disable it, this still happens. Any clue?

**Comment by 0aps** [comment]
@vasa137 were you able to figure a workaround for this?

**Comment by 0aps** [comment]
@RodrigoSMarques still happening in the latest release. Only happens in Android.

**Comment by RodrigoSMarques** [comment]
@0aps 

This plugin calls functions from the Branch Native SDK on each platform.

The Native SDK is responsible for monitoring the deeplinks, retrieving the response and returning it to the plugin. The plugin receives the data and forwards it to the Flutter application.

In this case, it is not a problem with the plugin but with the Branch SDK that is not returning the data.

Open a support ticket for Branch at the [link](https://help.branch.io/using-branch/page/submit-a-ticket) or open an issue in the platform repository:

- iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
- Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)
